package uni.app.dondeestacionomobile.model.enumerate

enum class TypeRoutePermit(val value: String) {
    PROHIBIDO_ESTACIONAR("PROHIBIDO ESTACIONAR"),
    PROHIBIDO_ESTACIONAR_DETENERSE("PROHIBIDO ESTACIONAR Y DETENERSE"),
    PERMITIDO_ESTACIONAR("PERMITIDO ESTACIONAR"),
    PERMITIDO_ESTACIONAR_90_GRADO("PERMITIDO ESTACIONAR A 90°"),
    PERMITIDO_ESTACIONAR_45_GRADO("PERMITIDO ESTACIONAR A 45°");
}
